on: [push, pull_request]
name: CI
jobs:
  golangci:
    name: lint
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  gomod:
    name: check go.mod
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          go mod tidy
          if [ -n "$(git status --porcelain)" ]; then
            echo 'running "go mod tidy" resulted in changes. Run "go mod tidy" locally and commit the changes.'
            exit 1
          fi
  test:
    name: test
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        env:
          GOOS: linux
        run: go test ./... -race